accounts:
  - name: validator1
    coins: ["20000milli", "200000000vmilli"]
  - name: faucet
    coins: ["10000milli", "100000000vmilli"]
validator:
  name: validator1
  staked: "100000000vmilli"
client:
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: faucet
  coins: ["5milli"]
build:
  main: "cmd/wasmd"
genesis:
  chain_id: "millicent"
  app_state:
    staking:
      params:
        bond_denom: "vmilli"